export const tableData = [
  {
    id: 1,
    starClass: "inbox-started",
    bookMark: "",
    subject: "Tim Reid, S P N",
    description: "Boost Your Website Traffic ",
    date: "April 01",
    className: "",
  },
  {
    id: 2,
    starClass: "inbox-started",
    bookMark: "",
    subject: "Freelancer.com",
    description: "Stop wasting your visitors",
    date: "May 23",
    className: "",
  },
  {
    id: 3,
    starClass: "",
    bookMark: "text-danger",
    subject: "PHPClass",
    description: "Added a new className: Login Class Fast Site",
    date: "9:27 AM",
    className: "unread",
  },
  {
    id: 4,
    starClass: "",
    bookMark: "",
    subject: "Facebook",
    description: "Somebody requested a new password",
    date: "June 13",
    className: "",
  },
  {
    id: 5,
    starClass: "inbox-started",
    bookMark: "",
    subject: "Skype",
    description: "Password successfully changed",
    date: "March 24",
    className: "",
  },
  {
    id: 6,
    starClass: "inbox-started",
    bookMark: "",
    subject: "Google+",
    description: "alireza, do you know",
    date: "March 09",
    className: "",
  },
  {
    id: 7,
    starClass: "inbox-started",
    bookMark: "",
    subject: "WOW Slider ",
    description: "New WOW Slider v7.8 - 67% off",
    date: "March 14",
    className: "",
  },
  {
    id: 8,
    starClass: "inbox-started",
    bookMark: "",
    subject: "LinkedIn Pulse",
    description: "The One Sign Your Co-Worker Will Stab",
    date: "Feb 19",
    className: "",
  },
  {
    id: 9,
    starClass: "",
    bookMark: "",
    subject: "Google Webmaster",
    description: "Improve the search presence of WebSite",
    date: "March 15",
    className: "unread",
  },
  {
    id: 10,
    starClass: "",
    bookMark: "",
    subject: "JW Player",
    description: "Last Chance: Upgrade to Pro for",
    date: "March 15",
    className: "",
  },
  {
    id: 11,
    starClass: "",
    bookMark: "",
    subject: "Drupal Community",
    description: "Welcome to the Drupal Community",
    date: "March 04",
    className: "",
  },
  {
    id: 12,
    starClass: "inbox-started",
    bookMark: "",
    subject: "Zoosk",
    description: "7 new singles we think you'll like",
    date: "May 14",
    className: "",
  },
  {
    id: 13,
    starClass: "",
    bookMark: "text-danger",
    subject: "LinkedIn",
    description: "Alireza: Nokia Networks, System Group and",
    date: "February 25",
    className: "",
  },
  {
    id: 14,
    starClass: "",
    bookMark: "",
    subject: "Facebook",
    description: "Your account was recently logged into",
    date: "March 14",
    className: "",
  },
  {
    id: 15,
    starClass: "",
    bookMark: "",
    subject: "Twitter",
    description: "Your Twitter password has been changed",
    date: "April 07",
    className: "",
  },
  {
    id: 16,
    starClass: "",
    bookMark: "",
    subject: "InternetSeer",
    description: "Performance Report",
    date: "July 14",
    className: "",
  },
  {
    id: 17,
    starClass: "",
    bookMark: "text-danger",
    subject: "Bertina",
    description: "IMPORTANT: Don't lose your domains!",
    date: "June 16",
    className: "",
  },
  {
    id: 18,
    starClass: "inbox-started",
    bookMark: "text-danger",
    subject: "Laura Gaffin, S P N ",
    description: "Your Website On Google (Higher Rankings Are Better)",
    date: "August 10",
    className: "",
  },
  {
    id: 19,
    starClass: "",
    bookMark: "",
    subject: "Facebook",
    description: "Alireza Zare Login faild",
    date: "feb 14",
    className: "",
  },
  {
    id: 20,
    starClass: "inbox-started",
    bookMark: "",
    subject: "AddMe.com",
    description: "Submit Your Website to the AddMe Business Directory",
    date: "August 10",
    className: "",
  },
  {
    id: 21,
    starClass: "",
    bookMark: "",
    subject: "Terri Rexer, S P N",
    description: "Forget Google AdWords: Un-Limited Clicks fo",
    date: "April 14",
    className: "",
  },
];
